@Restaurants.API_HostAddress = http://localhost:5161

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{Restaurants.API_HostAddress}}/weatherforecast/007/example

###

@name=string
GET {{Restaurants.API_HostAddress}}/query?name=gokul

###
